### ISSUE TITLE
redis synchronization timeout in smallfile

### ISSUE THREAD

**Issue by bengland2** [cloud-bulldozer/snafu#159]
I love the new redis sync feature in smallfile, very important.   But when I run a big test (more below) with smallfile, I get the  timeout below from all the smallfile pods.   But if I cut the number of files to 1/10 of that, then the test succeeds.   I think the redis_timeout environment variable (default 60 sec) may need to be adjusted in cases like this.   This can be done by editing resources/operator.yaml env: section, but it requires restarting the operator.   Is there a better way?

```
2020-03-24T00:14:16Z - INFO     - MainProcess - trigger_smallfile: Complete message from channel: {'type': 'su
bscribe', 'pattern': None, 'channel': b'smallfile-22b7124d-c3c5-5849-adb1-76056dabaa0f', 'data': 1}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 190, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/local/lib/python3.6/site-packages/redis/_compat.py", line 71, in recv
    return sock.recv(*args, **kwargs)
socket.timeout: timed out
```

This is followed by:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/snafu/run_snafu.py", line 137, in <module>
    sys.exit(main())
  File "/opt/snafu/run_snafu.py", line 86, in main
    parser))
  File "/opt/snafu/utils/py_es_bulk.py", line 156, in streaming_bulk
    for ok, resp_payload in streaming_bulk_generator:
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 212, in streaming_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 63, in _chunk_actions
    for action, data in actions:
  File "/opt/snafu/utils/py_es_bulk.py", line 117, in actions_tracking_closure
    for cl_action in cl_actions:
  File "/opt/snafu/run_snafu.py", line 119, in process_generator
    for action, index in data_object.emit_actions():
  File "/opt/snafu/smallfile_wrapper/trigger_smallfile.py", line 165, in emit_actions
    for msg in p.listen():
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3553, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3453, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3427, in _execute
    return command(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 316, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 248, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 204, in _read_from_socket
    raise TimeoutError("Timeout reading from socket")
redis.exceptions.TimeoutError: Timeout reading from socket
```
The CR is:

```
[root@e24-h17-740xd ripsaw]# more ../smf.yaml 
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: smf-benchmark-big
  namespace: my-ripsaw
spec:
  test_user: BenE
  clustername: bm-alias-cloud02-2020-03-23
  elasticsearch:
    server: snafu:ripsaw@marquez.perf.lab.eng.rdu2.redhat.com
    port: 9200
  es_index: ripsaw-smallfile
  workload:
    name: smallfile
    args:
      clients: 35
      samples: 3
      operation: ["create", "read"]
      threads: 3
      file_size: 1024
      files: 20000
      storageclass: example-storagecluster-cephfs
      storagesize: 500Gi
```

**Comment by bengland2** [comment]
and [this pastebin is an example of why the timeout occurs](http://pastebin.test.redhat.com/847927).
